version: "3.2"
services:
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/recurring
  web:
    build: .
    environment:
      RAILS_ENV: production
      # command: rails server -p 3000 -b '0.0.0.0'
      command: bundle exec unicorn -p 3000
    volumes:
      - .:/recurring
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  postgresql-data:
    external: true
  redis:
    external: true